### PR TITLE
Process of migrating to gradle - update gradle to 5.4.1

### PR DESCRIPTION
**Pull request by jaredsburrows**
#445

@shashachu

Update gradle to 5.4.1

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Moving forward, please ensure the validity of the Gradle wrapper jar before merging in the future.

I know @jaredsburrows is trusted, but in general, a PR with a giant blob of binary should always be checked for validity.

https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification

**Comment by jaredsburrows** [comment]
You would think that this would be build into the wrapper.

**Comment by shashachu** [comment]
@JLLeitschuh good call-out. Thanks

**Comment by JLLeitschuh** [comment]
> You would think that this would be build into the wrapper.

You're referring to the `gradlew` and `gradlew.bat` files? It could be done that way, but then every Gradle launch would have the added overhead of an SHA checksum check and network access.

Feel free to open an issue with gradle/gradle if you want to discuss this idea and I can discuss it with the team internally. (I start with Gradle officially on June 17th).

**Pull request merged**
