### PR TITLE
Simple property assignments in KTS

### PR DESCRIPTION
**Pull request by Goooler**
## Description

Follow up #2105.

https://blog.gradle.org/simpler-kotlin-dsl-property-assignment

## Checklist

Before submitting the PR, please check following (checks which are not relevant may be ignored):
- [ ] Commit message are well written. In addition to a short title, the commit message also explain why a change is made.
- [ ] At least one commit message contains a reference `Closes #<xxx>` or `Fixes #<xxx>` (replace`<xxx>` with issue number)
- [ ] Tests are added
- [ ] KtLint format has been applied on source code itself and violations are fixed
- [ ] `CHANGELOG.md` is updated
- [x] PR description added

[Documentation](https://pinterest.github.io/ktlint/) is updated. See [difference between snapshot and release documentation](https://github.com/pinterest/ktlint/tree/master/documentation)
- [ ] [Snapshot documentation](https://github.com/pinterest/ktlint/tree/master/documentation/snapshot) in case documentation is to be released together with a code change
- [ ] [Release documentation](https://github.com/pinterest/ktlint/tree/master/documentation/release-latest) in case documentation is related to a released version of ktlint and has to be published as soon as the change is merged to master 
- [ ] In case of adding a new rule, it needs to be added to [experimental rules documentation](https://pinterest.github.io/ktlint/latest/rules/experimental/)

### CODE REVIEW

**Comment by paul-dingemans** [comment]
> https://blog.gradle.org/simpler-kotlin-dsl-property-assignment

states:
> It’s important to note that the feature is still marked as incubating. Changes to the feature are possible, although unlikely. We don’t recommend using this feature in published plugins until it’s marked as stable (likely in Gradle 8.3).
> 
> Lazy property assignment is supported in IntelliJ 2022.3 (2023.1.1 or newer is recommended) and Android Studio Giraffe (or newer).

I have some doubts whether we already should try this out in our build or that we should wait until the stable release. Is there a pressing need, not to wait?

**Comment by Goooler** [comment]
Either way, I also filed it to https://github.com/detekt/detekt/pull/6251.

**Comment by paul-dingemans** [comment]
In Gradle 8.3, this feature is still marked as unstable.

**Comment by Goooler** [comment]
Yeah.

**Comment by Goooler** [comment]
Some of this feature had been used in https://github.com/pinterest/ktlint/blob/460c6358cdf15bc02d1921b572e8b23c1b4a722c/build-logic/src/main/kotlin/ktlint-kotlin-common.gradle.kts#L31

Maybe it's time to land this.

**Comment by Goooler** [comment]
It's stable after #2294 merged.

**Pull request merged**
