### PR TITLE
Simplify BOM exclude list

### PR DESCRIPTION
**Pull request by Goooler**
## Description

Simplify the code below:
```kt
val internalNonPublishableProjects: Set<String> by rootProject.extra
val excludeList = internalNonPublishableProjects + "ktlint-test-ruleset-provider-v2-deprecated"
```

## Checklist

Before submitting the PR, please check following (checks which are not relevant may be ignored):
- [x] Commit message are well written. In addition to a short title, the commit message also explain why a change is made.
- [ ] At least one commit message contains a reference `Closes #<xxx>` or `Fixes #<xxx>` (replace`<xxx>` with issue number)
- [ ] Tests are added
- [ ] KtLint format has been applied on source code itself and violations are fixed
- [x] PR title is short and clear (it is used as description in the release changelog)
- [x] PR description added (background information)

[Documentation](https://pinterest.github.io/ktlint/) is updated. See [difference between snapshot and release documentation](https://github.com/pinterest/ktlint/tree/master/documentation)
- [ ] [Snapshot documentation](https://github.com/pinterest/ktlint/tree/master/documentation/snapshot) in case documentation is to be released together with a code change
- [ ] [Release documentation](https://github.com/pinterest/ktlint/tree/master/documentation/release-latest) in case documentation is related to a released version of ktlint and has to be published as soon as the change is merged to master

### CODE REVIEW

**Comment by Goooler** [comment]
```sh
diff ktlint-bom-1.1.0-SNAPSHOT.pom.before ktlint-bom-1.1.0-SNAPSHOT.pom.after
```

`ktlint-bom-1.1.0-SNAPSHOT.pom.after`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- This module was also published with a richer model, Gradle metadata,  -->
  <!-- which should be used instead. Do not delete the following line which  -->
  <!-- is to indicate to Gradle or any Gradle module metadata file consumer  -->
  <!-- that they should prefer consuming it instead. -->
  <!-- do_not_remove: published-with-gradle-metadata -->
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.pinterest.ktlint</groupId>
  <artifactId>ktlint-bom</artifactId>
  <version>1.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>ktlint-bom</name>
  <description>An anti-bikeshedding Kotlin linter with built-in formatter.</description>
  <url>https://github.com/pinterest/ktlint</url>
  <licenses>
    <license>
      <name>MIT</name>
      <url>https://opensource.org/licenses/MIT</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <developers>
    <developer>
      <id>pinterest</id>
      <name>Pinterest, Inc.</name>
    </developer>
  </developers>
  <scm>
    <connection>scm:git:git://github.com/pinterest/ktlint.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/pinterest/ktlint.git</developerConnection>
    <url>https://github.com/pinterest/ktlint</url>
  </scm>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-reporter-baseline</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-reporter-checkstyle</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-reporter-core</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-reporter-format</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-reporter-html</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-reporter-json</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-reporter-plain</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-reporter-plain-summary</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-reporter-sarif</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-cli-ruleset-core</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-logger</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-rule-engine</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-rule-engine-core</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-ruleset-standard</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.pinterest.ktlint</groupId>
        <artifactId>ktlint-test</artifactId>
        <version>1.1.0-SNAPSHOT</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>

```

**Comment by Goooler** [comment]
@paul-dingemans Failure may be related to the project version, can you bump this to Snapshot first?

https://github.com/pinterest/ktlint/blob/48cc83b7eb786be88d3a2f743372583cd30cc2e0/gradle.properties#L1

**Comment by paul-dingemans** [comment]
> @paul-dingemans Failure may be related to the project version, can you bump this to Snapshot first?
> 
> https://github.com/pinterest/ktlint/blob/48cc83b7eb786be88d3a2f743372583cd30cc2e0/gradle.properties#L1

Ouch, good catch. I did forget to apply the last step in the release process. I will update it and push the change to your branch once merged.

**Comment by Goooler** [comment]
Wrongly rebased.

**Pull request merged**
