### PR TITLE
Remove verification-metadata.xml

### PR DESCRIPTION
**Pull request by Goooler**
## Description

There are some reasons to remove this:
- After removing it, we can enable @renovate-bot for this repo, cause it doesn't support the verification.
- Seems code highlighting in `build-logic` doesn't work as `checksums are missing from verification metadata for gradle-8.0.1-src.zip` which is added by IDEA.
- Verification task doesn't support CC, which has been enabled by #1879.
- Avoid unnecessary verification metadata changes in PRs.

## Checklist

- [x] PR description added
- [ ] tests are added
- [ ] KtLint has been applied on source code itself and violations are fixed
- [ ] [documentation](https://pinterest.github.io/ktlint/) is updated
- [ ] `CHANGELOG.md` is updated

In case of adding a new rule:
- [ ] Rule is added to [rules documentation](https://pinterest.github.io/ktlint/rules/standard/)

### CODE REVIEW

**Comment by Goooler** [comment]
CI builds are much faster after enabling CC.

**Comment by paul-dingemans** [comment]
> CI builds are much faster after enabling CC.

@Goooler, Is there a specific reason that you tagged @shashachu? What do you expect from her?

**Comment by Goooler** [comment]
Let's use Renovate for now.

**Comment by shashachu** [comment]
Ok thanks for your patience. I had a quick sync w/ our security team and they agree that keeping dependencies up to date is more important than dependency verification. So we can go ahead and merge this.

**Comment by Goooler** [comment]
@shashachu Can you enable Renovate for this repo? Need to grant it in account settings.

**Comment by shashachu** [comment]
@Goooler @paul-dingemans finally heard back from our admin and they enabled it on this repo: 
image

Is there any action i need to take as a repository admin?

**Comment by paul-dingemans** [comment]
I don't think so. There is already an [on-boarding PR created by Renovate](https://github.com/pinterest/ktlint/pull/2027). We will let you know when we need additional configuration.

**Comment by Goooler** [comment]
That's the config file, after merging, the dependency update PRs will be sent.

**Pull request merged**
