### PR TITLE
fix indentation rule has problems with ignoring braces

### PR DESCRIPTION
**Pull request by zsqw123**
## Description

fix ktlint indentation rule has problems with ignoring braces #1644 

## Checklist

- [x] PR description added
- [x] tests are added
- [x] KtLint has been applied on source code itself and violations are fixed
- [ ] [documentation](https://pinterest.github.io/ktlint/) is updated
- [x] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by paul-dingemans** [comment]
Thx for your contribution. I like the idea. The way it is implemented is a bit hard to understand. So I will refactor your solution before merging.

**Comment by zsqw123** [comment]
In fact, my idea is simple. I just change the logic of suppress from never `visit` to never `emit`. And I tested it locally, and it passed the unit test.

**Comment by paul-dingemans** [comment]
> In fact, my idea is simple. I just change the logic of suppress from never `visit` to never `emit`. And I tested it locally, and it passed the unit test.

Yes the idea is solid and your solution worked fine! I wanted a different implementation so that the logic for determining the new autoCorrect and emit values in a single place (now in the SuppressHandler).

**Comment by zsqw123** [comment]
#1644 is different from #1645. This pr fixes #1644 only

**Pull request merged**
