### PR TITLE
Replace usage of arrayOf with array literal.

### PR DESCRIPTION
**Pull request by Tapchicoma**
And made command line options style consistent.

### CODE REVIEW

**Comment by shashachu** [comment]
Is there a reason why array literals are preferred?

**Comment by jaredsburrows** [comment]
@shashachu The Kotlin plugin in the IDE shows this suggestion.

**Comment by Tapchicoma** [comment]
> @shashachu The Kotlin plugin in the IDE shows this suggestion.

Yes, that was main trigger for me.

Imho, visually, it looks better in annotations parameters, then `arrayOf(..)`.

**Comment by shashachu** [comment]
Ah ok I just did some research and array literal syntax is only supported for annotations, and only since Kotlin 1.2. I guess people just thought `arrayOf` in annotations looked ugly. :)

**Comment by shashachu** [comment]
lgtm, thanks!

**Pull request merged**
