### PR TITLE
Improve ktlint performances when the input patterns are absolute paths

### PR DESCRIPTION
**Pull request by rciovati**
## Description

This PR proposes a solution for the performance issue described in #1135.

When ktlint gets a bunch of absolute paths there is no need to walk through the file system and search for them, we can just resolve and analyze them directly.

Before:

```
➜  android-listeners git:(rc/kitlint) ktlint -F --debug --relative MyFile.kt
[DEBUG] Discovered ruleset with "standard" id.
[DEBUG] Discovered reporter with "baseline" id.
[DEBUG] Discovered reporter with "checkstyle" id.
[DEBUG] Discovered reporter with "json" id.
[DEBUG] Discovered reporter with "html" id.
[DEBUG] Discovered reporter with "plain" id.
[DEBUG] Initializing "plain" reporter with {verbose=true, color=false, color_name=DARK_GRAY}
[DEBUG] Checking MyFile.kt
Loaded .editorconfig: [insert_final_newline: true, max_line_length: 200]
[DEBUG] 30291ms / 1 file(s) / 0 error(s)
```

After:
```
➜  android-listeners git:(rc/kitlint) java -jar ktlint-0.42.0-SNAPSHOT-all.jar -F --debug --relative MyFile.kt
[DEBUG] Discovered ruleset with "standard" id.
[DEBUG] Discovered reporter with "baseline" id.
[DEBUG] Discovered reporter with "checkstyle" id.
[DEBUG] Discovered reporter with "json" id.
[DEBUG] Discovered reporter with "html" id.
[DEBUG] Discovered reporter with "plain" id.
[DEBUG] Initializing "plain" reporter with {verbose=true, color=false, color_name=DARK_GRAY}
[DEBUG] Checking MyFile.kt
Loaded .editorconfig: [insert_final_newline: true, max_line_length: 200]
[DEBUG] 847ms / 1 file(s) / 0 error(s)
```

In our project it speeds up the execution from ~30s down to less than 1s.

No additional tests were added, the exist ones passes.

## Checklist

- [ ] tests are added
- [ ] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by rciovati** [comment]
it looks like the build fails because of a dependency verification issue which I believe is not related to my change but I'll see what I can do.

```
For more details see https://docs.gradle.org/6.8.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
Dependency verification is an incubating feature.
> Task :buildSrc:extractPrecompiledScriptPluginPlugins
> Task :buildSrc:generateExternalPluginSpecBuilders FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildSrc:generateExternalPluginSpecBuilders'.
> Dependency verification failed for configuration ':buildSrc:compileClasspath'
  2 artifacts failed verification:
    - dokka-gradle-plugin-0.10.1.jar (org.jetbrains.dokka:dokka-gradle-plugin:0.10.1) from repository MavenRepo
    - dokka-gradle-plugin-0.10.1.pom (org.jetbrains.dokka:dokka-gradle-plugin:0.10.1) from repository MavenRepo
  If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/6.8.3/userguide/dependency_verification.html#sec:troubleshooting-verification
  
  Open this report for more details: file:///home/runner/work/ktlint/ktlint/build/reports/dependency-verification/at-1620670437192/dependency-verification-report.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 49s
Error: Process completed with exit code 1.
```

**Comment by shashachu** [comment]
@rciovati thanks so much for this change. I just merged a PR which should fix the CI builds; can you rebase?

**Review by shashachu — APPROVED** [review]

**Comment by rciovati** [comment]
@shashachu rebased, thanks!

**Review by greggiacovelli — APPROVED** [review]

**Review by shashachu — APPROVED** [review]

**Comment by shashachu** [comment]
argh. windows build failing. 🤦‍♀️

**Comment by shashachu** [comment]
@rciovati do you have this commit rebased in? https://github.com/pinterest/ktlint/pull/1152/commits/fae23623a692c897f44cea91aed441dc60625921 

It might be the same issue.

**Comment by rciovati** [comment]
@shashachu I've just rebased one more time!

**Comment by shashachu** [comment]
haha it's killing me! i'm not sure what's happening with the dependency verification...

**Comment by Tapchicoma** [comment]
@rciovati could you rebase again? This time verification should pass

**Comment by Tapchicoma** [comment]
@rciovati tests are failing, could you update your change, so they will pass?

**Comment by rciovati** [comment]
@Tapchicoma I'll try. I don't have a windows machine so this might take a while.

**Comment by shashachu** [comment]
@rciovati @Tapchicoma `Path.resolve` seems to throw an exception on Windows when you pass in file globs. This change makes the tests pass; does it seem valid or too hacky?

```
val (existingFiles, actualGlobs) = globs.partition {
        try {
            Files.isRegularFile(rootDir.resolve(it))
        } catch (e: InvalidPathException) {
            false
        }
    }
```

**Comment by rciovati** [comment]
@shashachu it looks valid to me! I've just pushed the change. Thank you so much for looking into this one 🙏

**Comment by shashachu** [comment]
@rciovati looks like you are missing an import :) `e: /home/runner/work/ktlint/ktlint/ktlint/src/main/kotlin/com/pinterest/ktlint/internal/FileUtils.kt: (31, 21): Unresolved reference: InvalidPathException`

**Comment by rciovati** [comment]
@shashachu of course 🤦  fixed

**Comment by shashachu** [comment]
hallelujah! thanks @rciovati for your patience!

**Pull request merged**
