### PR TITLE
Run tests parallelly on CI

### PR DESCRIPTION
**Pull request by Goooler**
## Description

This is a regression of using toolchain, reverts some changes in #1294 & #1453 to save more time on CI, especially for the Windows related builds. More result diffs you can see https://github.com/Goooler/ktlint/pull/39.

## Checklist

- [x] PR description added
- [ ] tests are added
- [ ] KtLint has been applied on source code itself and violations are fixed
- [ ] [documentation](https://pinterest.github.io/ktlint/) is updated
- [ ] `CHANGELOG.md` is updated

In case of adding a new rule:
- [ ] Rule is added to [rules documentation](https://pinterest.github.io/ktlint/rules/standard/)

### CODE REVIEW

**Comment by shashachu** [comment]
@Goooler i fixed the issue with the PR build; you should be able to rebase and re-run the checks.

**Comment by paul-dingemans** [comment]
@Goooler Can you have another look? I think the 'old' jobs need to be removed as the build now keeps waiting.

**Comment by Goooler** [comment]
That might be related to the status check in repo settings, see https://stackoverflow.com/a/69169858/19772203.

@shashachu Can you take a look this in settings?

**Comment by Goooler** [comment]
No need to note this change, it's not user noticeable.

**Comment by shashachu** [comment]
@Goooler @paul-dingemans  i updated the required checks for merging. we will have to update this whenever we change the build jdk versions, but that shouldn't be a huge deal. 

thanks for this change! i have also noticed the windows build takes forever now.

**Comment by shashachu** [comment]
For future reference (for myself and any other admins we may add in the future), the checks are in Settings -> Branches -> Branch protection rules (master). I had to delete the old checks and add the new ones here:

image

**Pull request merged**
