### PR TITLE
add html reporter module to ktlint library

### PR DESCRIPTION
**Pull request by arrmixer**
in reference to #399  and https://github.com/mcassiano/ktlint-html-reporter/issues/19. 
Add  mcassiano's html reporter to ktlint repo.

### CODE REVIEW

**Comment by mcassiano** [comment]
Nice :) thanks for taking this on!

**Comment by arrmixer** [comment]
Yeah no prob! Thanks for coaching me through it! 💪🏼

**Comment by shashachu** [comment]
@mcassiano @arrmixer apologies for the delay - just merged this in. Thanks for the contribution!

**Comment by arrmixer** [comment]
Your welcome! I’m happy I could help. And excited I was able to contribute!

**Pull request merged**
