### PR TITLE
Create codeql.yml

### PR DESCRIPTION
**Pull request by paul-dingemans**
## Description

Try out codeql analysis workflow

## Checklist

Before submitting the PR, please check following (checks which are not relevant may be ignored):
- [X] Commit message are well written. In addition to a short title, the commit message also explain why a change is made.
- [ ] At least one commit message contains a reference `Closes #<xxx>` or `Fixes #<xxx>` (replace`<xxx>` with issue number)
- [ ] Tests are added
- [ ] KtLint format has been applied on source code itself and violations are fixed
- [ ] `CHANGELOG.md` is updated
- [ ] PR description added

[Documentation](https://pinterest.github.io/ktlint/) is updated. See [difference between snapshot and release documentation](https://github.com/pinterest/ktlint/tree/master/documentation)
- [ ] [Snapshot documentation](https://github.com/pinterest/ktlint/tree/master/documentation/snapshot) in case documentation is to be released together with a code change
- [ ] [Release documentation](https://github.com/pinterest/ktlint/tree/master/documentation/release-latest) in case documentation is related to a released version of ktlint and has to be published as soon as the change is merged to master 
- [ ] In case of adding a new rule, it needs to be added to [experimental rules documentation](https://pinterest.github.io/ktlint/latest/rules/experimental/)

### CODE REVIEW

**Comment by Goooler** [comment]
Consider Detekt?

**Comment by paul-dingemans** [comment]
> Consider Detekt?

Yeah, maybe later

**Comment by binkley** [comment]
The PR branch build fails with CodeQL.
What code problems would you like to address?

**Comment by paul-dingemans** [comment]
I was just trying it out. I have no idea what is possible with this tool. So I cannot answer your question

**Pull request closed without merging**
