### PR TITLE
Bump setup-java actions to v3

### PR DESCRIPTION
**Pull request by Goooler**
## Description

https://github.com/actions/setup-java/releases/tag/v3.0.0

## Checklist

- [ ] tests are added
- [ ] `CHANGELOG.md` is updated

### CODE REVIEW

**Review by See887777 — APPROVED** [review]

**Comment by paul-dingemans** [comment]
@Goooler Tnx for your contribution. Can you please chekc why the "Validation" step is not completed? It is still `Waiting for status to be reported`.

**Comment by Goooler** [comment]
Seems like this issue: https://github.community/t/expected-waiting-for-status-to-be-reported/16727

**Comment by paul-dingemans** [comment]
I am not sure what you expect to happen? Do you think that a manual action is needed? If so, what action? I can not find anything about protected branches as is suggested in https://github.community/t/github-actions-pull-requests-always-include-some-outdated-checks/16157. Maybe, I am not authorized for that.

**Comment by Goooler** [comment]
Alright, just be housekeeping.

**Pull request closed without merging**
