### PR TITLE
Support custom rulesets and reporters on Java 9+

### PR DESCRIPTION
**Pull request by jacquerie**
Closes https://github.com/pinterest/ktlint/issues/259
Supersedes and closes https://github.com/pinterest/ktlint/pull/495

Abandons completely the approach of https://github.com/pinterest/ktlint/pull/351 in favor of [a simpler idea](https://github.com/pinterest/ktlint/pull/495#issuecomment-528249221) proposed by @Tapchicoma.

Tested by first building the `ktlint-ruleset-template.jar` and then running
```
$ ./gradlew ktlint --args="--ruleset ~/Code/ktlint/ktlint-ruleset-template/build/libs/ktlint-ruleset-template.jar ~/Code/ktlint/ktlint/src/**/*.kt"
```

### CODE REVIEW

**Comment by Tapchicoma** [comment]
I see following warning, when running on OpenJDK 11.0.4:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.pinterest.ktlint.KtlintCommandLine (file:/command/ktlint/build/run/ktlint) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of com.pinterest.ktlint.KtlintCommandLine
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Another thing, I've noticed, is with this approach custom ruleset violations are not failing the build :disappointed:

**Comment by Tapchicoma** [comment]
I think, I found a solution. Will open a PR soon.

**Comment by shashachu** [comment]
sorry for the delay- i just merged in @Tapchicoma 's PR - will this unblock you?

**Comment by jacquerie** [comment]
> sorry for the delay- i just merged in @Tapchicoma 's PR - will this unblock you?

Great, thanks! Well, the last step would be to get a `0.35.0` release containing this fix... but I guess I just need to wait for it to happen.

**Comment by shashachu** [comment]
> > sorry for the delay- i just merged in @Tapchicoma 's PR - will this unblock you?
> 
> Great, thanks! Well, the last step would be to get a `0.35.0` release containing this fix... but I guess I just need to wait for it to happen.

If you like, you should be able to use a snapshot version of ktlint (see the README) to verify that it works until we release 0.35.0. There are a couple bugs I'd like to squash before our next release.

**Comment by jacquerie** [comment]
> If you like, you should be able to use a snapshot version of ktlint (see the README) to verify that it works until we release 0.35.0.

I'd love to, but we use `ktlint` through `gradle-ktlint`, so I ran into the issue that this PR will fix: https://github.com/JLLeitschuh/ktlint-gradle/pull/281. So I'll still have to wait, either for a new version of `ktlint` or a new version of `gradle-ktlint` !

**Pull request closed without merging**
