### PR TITLE
Update and add 'ktlint-ruleset-template' to settings.gradle

### PR DESCRIPTION
**Pull request by jaredsburrows**
@shashachu

### CODE REVIEW

**Comment by shashachu** [comment]
Since you're working on the template project, can you fix the `RuleSetProvider` file (like I did here https://github.com/pinterest/ktlint/pull/485/files#diff-4b459340022d965aebf12c424f0bd97b)

Once this is merged, I'll rebase and drop it from my PR.

**Comment by jaredsburrows** [comment]
Do you want me to patch your code?

**Comment by shashachu** [comment]
You don't need to patch in the whole diff, just the Ruleset provider in the template. Or you can just leave it and I'll do it as part of my PR.

**Comment by jaredsburrows** [comment]
Can we just merge this separately?

**Comment by shashachu** [comment]
> Can we just merge this separately?

Sure, no problem. I can keep it in my PR; it makes reasonable sense there.

**Pull request merged**
