### PR TITLE
Use Junit4 instead of TestNG

### LINKED ISSUE #447: Use Junit 4/5, instead of TestNG

### PR DESCRIPTION
**Pull request by jaredsburrows**
@shashachu 
Closes #447

### CODE REVIEW

**Comment by arturbosch** [comment]
Just out of curiosity, why the change from testng to junit4?

**Comment by jaredsburrows** [comment]
It is the default test suite for Gradle and I want to finish migrating this to gradle. Also your project, detekt uses Junit as well :).

**Comment by JLLeitschuh** [comment]
No love for JUnit 5?

I've been actively adding features to make using Junit 5 with Kotlin nicer.

https://junit.org/junit5/

**Comment by jaredsburrows** [comment]
@shashachu This is rebased.

**Comment by jaredsburrows** [comment]
@JLLeitschuh Junit 5 can come after this is merged. Maybe this can be the first step?

**Pull request merged**
