### PR TITLE
Indentation rule fixes

### PR DESCRIPTION
**Pull request by paul-dingemans**
This PR fixes the indentation problems mentioned in #575 and tab indentation problems. Also a lot of unit tests have been added to check the tab indentation.

Examples of code blocks will be auto corrected by merging this PR.

Do not report tabs after indentation margin in multiline string (#575):
```
            val str =
                """
                ${'\t'}Tab at the beginning of this line but after the indentation margin
                Tab${'\t'}in the middle of this string
                Tab at the end of this line.${'\t'}
                """.trimIndent()
```

KDOC indentation
```
            class Foo {
                  /**
                    *
                     */
                fun foo() {}
            }
```

Improperly indented multiline strings:
```
            fun foo() {
              println("""
                line1
                    line2
                    """.trimIndent())
            }

            fun foo() {
                println("""
                    line1
                line2""".trimIndent())
            }

            fun foo() {
                println(
                    """
                """.trimIndent()
                )
            }

            fun foo() {
                println(
                    """
                text ""

                     text
                     ""
                """
                )
            }
```

Multiline string as property value:
```
            class C {
                val CONFIG_COMPACT1 = """
                        {
                        }
                    """.trimIndent()
                val CONFIG_COMPACT2 = // comment
                    """
                        {
                        }
                    """.trimIndent()
            }
```

Report (no autocorrect is possible) in case indentation of multiline string contains tabs and spaces like in example below:
```
                val foo = """
                      line1
                ${'\t'}line2
                    """.trimIndent()
```

Fix indentation of multiline string in case all lines in it are indented with the wrong indentation character only (or are blank):
```
            val str =
                """
            ${'\t'}line1
            ${'\t'}${'\t'}line2
                """.trimIndent()
```

Note: the lint-checking currently fails on file "IndentationRuleTrimIndentTest" only because the directive that disable the indent-rule from being executed on that file needs to be merged first (see this [pull request](https://github.com/pinterest/ktlint/pull/1038).

### CODE REVIEW

**Comment by romtsn** [comment]
The PR is aiming to fix multiple things and is also very hard to review in its current form - could you split it into small logical chunks?

**Comment by paul-dingemans** [comment]
I was afraid of that remark but I do understand it. I will give it a try and I am sure that I can split off some minor changes. But the core change of the indentRule, e.g. method indentStringTemplate will still be a complex and very intertwined change. It would be great if you in mean time can merge [PR fix ktlint-disable](https://github.com/pinterest/ktlint/pull/1038) as it will be blocking for core problem as well.

**Comment by Tapchicoma** [comment]
Regarding #1038 - I wanted to check it in a few days. Probably the logic there need to revised and have more clear use-cases.

**Comment by paul-dingemans** [comment]
> I was afraid of that remark but I do understand it. I will give it a try and I am sure that I can split off some minor changes. But the core change of the indentRule, e.g. method indentStringTemplate will still be a complex and very intertwined change. It would be great if you in mean time can merge [PR fix ktlint-disable](https://github.com/pinterest/ktlint/pull/1038) as it will be blocking for core problem as well.

Part 1: [fix indentation multiline string](https://github.com/pinterest/ktlint/pull/1052)

**Comment by paul-dingemans** [comment]
I am not sure how to proceed with the other parts. Some others part rely on part 1 to be merged with master. Should I wait till part 1 is merged to master? Or can I also submit a PR is branched off on top of part 1?

**Comment by romtsn** [comment]
Yeah you can submit a PR branched off of part 1 and also target part 1

**Comment by paul-dingemans** [comment]
This is my first open source project to which I am contributing. I do not understand how to create the PR for part2.

 On my local machine I have created a new branch 'multiline-string-indent-2' based on top of branch 'multiline-string-indent' and pushed those changes to my fork (https://github.com/paul-dingemans/ktlint/branches). When I am trying to create a PR in the master repository, I can not indicate that this PR should be compared with the 'multiline-string-indent' branch. See [image](https://imgur.com/a/HOBdawz). I do not want to use master as base because this PR should not be merged until part is merged.

I hope you can explain what I should do. Tnx in advance.

**Comment by romtsn** [comment]
I am sorry for misinforming you, you obviously can do it only on your own fork and not with the base ktlint repo. Then the only way would be to wait until we merge your first PR and then rebase and open following PRs on top

**Comment by paul-dingemans** [comment]
> I am sorry for misinforming you, you obviously can do it only on your own fork and not with the base ktlint repo. Then the only way would be to wait until we merge your first PR and then rebase and open following PRs on top

That is no problem. All followup PR's are ready to be pushed once the first part is merged. It would be really great if you can out that into motion.

**Comment by paul-dingemans** [comment]
Closing this PR while awaiting merge of https://github.com/pinterest/ktlint/pull/1052

**Pull request closed without merging**
