### PR TITLE
Move dependency declarations into a version catalog

### PR DESCRIPTION
**Pull request by Goooler**
## Description

Migrate to version catalog, easy to convert gradle build scripts to kts.

## Checklist

- [ ] tests are added
- [ ] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by shashachu** [comment]
@Tapchicoma opinions? I've never seen this particular format before.

**Comment by Goooler** [comment]
@shashachu See [Sharing dependency versions between projects](https://docs.gradle.org/current/userguide/platforms.html) and usage in [JLLeitschuh/ktlint-gradle](https://github.com/JLLeitschuh/ktlint-gradle/blob/master/gradle/libs.versions.toml).

**Comment by paul-dingemans** [comment]
> @shashachu See [Sharing dependency versions between projects](https://docs.gradle.org/current/userguide/platforms.html) and usage in [JLLeitschuh/ktlint-gradle](https://github.com/JLLeitschuh/ktlint-gradle/blob/master/gradle/libs.versions.toml).

@Goooler Tnx for the link. It looks interesting. I have checked out your branch on my local machine, but I am experiencing problems listed below. Most likely that is due to my very limited knowledge about Gradle ;-)

I am missing the ktlint gradle task to check for linting problems inside ktlint itself. I use to run it on my local machine via the Gradle Tool window by expanding the following path "ktlint > Tasks > verification > ktlint" and it should start task below:
```
task ktlint(type: JavaExec, group: LifecycleBasePlugin.VERIFICATION_GROUP) {
```

Also I would have expected that when I click on the dependency in a line like below, that IntelliJ would open up the file 'libs.versions.toml' at the specific line where 'junit5Api` was declared. However, none of those links do work for me.
```
testImplementation libs.junit5Api
```

**Comment by Goooler** [comment]
@paul-dingemans 
The first problem, I haven't seen the `ktlint` where applied, my changes should just affect deps declaration.
Second, code navigation does not work in groovy gradle, after migrate to kotlin build script, it will navigate to files generated by `libs.versions.toml` like below

image

**Comment by Goooler** [comment]
In follow-up PRs, I'll try to migrate gradle build script to kts.

**Comment by paul-dingemans** [comment]
> In follow-up PRs, I'll try to migrate gradle build script to kts.

Would it be an option for you, to work on that while we await feedback of other maintainers to review this PR? I have too little knowledge of our build process to judge this PR on my own.

**Comment by Goooler** [comment]
Ok.

**Pull request closed without merging**
