### PR TITLE
Update Kotlin development version to 1.7.20-beta / 1.7.10

### PR DESCRIPTION
**Pull request by paul-dingemans**
## Description

Update Kotlin development version to `1.7.20-beta` and Kotlin version to `1.7.10`.

## Checklist

- [X] PR description added
- [ ] tests are added
- [ ] KtLint has been applied on source code itself and violations are fixed
- [ ] [documentation](https://pinterest.github.io/ktlint/) is updated
- [X] `CHANGELOG.md` is updated

In case of adding a new rule:
- [ ] Rule is added to [rules documentation](https://pinterest.github.io/ktlint/rules/standard/)

### CODE REVIEW

**Comment by paul-dingemans** [comment]
@Goooler May I kindly request your help with this issue? 

Accodirding to https://github.com/pinterest/ktlint/runs/7827127989?check_suite_focus=true:
```
xecution failed for task ':buildSrc:generateExternalPluginSpecBuilders'.
> Task :buildSrc:generateExternalPluginSpecBuilders FAILED
> Dependency verification failed for configuration ':buildSrc:compileClasspath'
  2 artifacts failed verification:
    - kotlin-gradle-plugin-1.7.[20](https://github.com/pinterest/ktlint/runs/7827127989?check_suite_focus=true#step:7:21)-Beta-gradle71.jar (org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20-Beta) from repository MavenRepo
    - kotlin-gradle-plugin-api-1.7.20-Beta-gradle71.jar (org.jetbrains.kotlin:kotlin-gradle-plugin-api:1.7.20-Beta) from repository MavenRepo
  If the artifacts are trustworthy, you will need to update the gradle/verification-metadata.xml file by following the instructions at https://docs.gradle.org/7.4/userguide/dependency_verification.html#sec:troubleshooting-verification
  
  Open this report for more details: file:///home/runner/work/ktlint/ktlint/build/reports/dependency-verification/at-1660487803962/dependency-verification-report.html
```

I do understand that I need to add something to `verification-metadata.xml`, but I don't know what. I have tried to regenerate this files but this result in expanding the file from 326 lines to 2000+ lines. Any help, especially some explanation of how to resolve it myself would be appreciated.

**Comment by Goooler** [comment]
Try `./gradlew --write-verification-metadata pgp,sha256 help`, I was trying to buming Kotlin versions but tests failed, see https://github.com/Goooler/ktlint/pull/26.

**Comment by Goooler** [comment]
And you also need to bump the kotlin version in version catalog, see
https://github.com/pinterest/ktlint/blob/50d1d8c672f19c28112414426e2444724d9ccf32/gradle/libs.versions.toml#L4

**Comment by Goooler** [comment]
@paul-dingemans I tested this PR in https://github.com/Goooler/ktlint/pull/29, you can revert changes after b2a20419121e033ef7cc950435ee977389433254, and pick up 0510a0b3e688f6f3f267a46901e8a1eabf24515a to try again.

**Comment by paul-dingemans** [comment]
@Goooler Cool, it finally worked. Tnx for helping out! I am gonna try again with next Kotlin update where I can manage it without your help.

**Pull request merged**
