### PR TITLE
Adding new option disable-standard-rules

### PR DESCRIPTION
**Pull request by akuleshov7**
### What's done:
Adding special option `disable-standard-rules` that is extremely useful and needed when `ktlint` is used as a framework for static analysis. In some cases when `custom ruleset` is used - there is no need to use `standard ruleset` as it can lead to conflicts.

In this case we need a mechanism to disable standard rules. This change will not break any API and the default behavior will remain the same.

### CODE REVIEW

**Comment by akuleshov7** [comment]
@Tapchicoma please have a look when you will have a minute. Thanks!

**Comment by akuleshov7** [comment]
@romtsn Roma, may be you will have a chance to have a look?

**Comment by romtsn** [comment]
@akuleshov7 looks reasonable (for your case), but what do you think of extending `disabled_rules` option so you can also pass a ruleset name there (not only rules name)? then we could just `--disabled_rules=standard` and not introduce a new cli option

**Comment by akuleshov7** [comment]
> @akuleshov7 looks reasonable (for your case), but what do you think of extending `disabled_rules` option so you can also pass a ruleset name there (not only rules name)? then we could just `--disabled_rules=standard` and not introduce a new cli option

Рома, updated, please have a look. This looks a little bit less user-friendly, but works fine,

**Comment by romtsn** [comment]
Looks fine to me, but PR needs a fix :)

**Comment by akuleshov7** [comment]
> Looks fine to me, but PR needs a fix :)
Oh, I have violated code formatting in code formatter, lol :D

@romtsn Fixed

**Pull request merged**
