### PR TITLE
Fix indentation of delegated super type call entry

### LINKED ISSUE #1210: Internal Error when upgrading from 0.41.0 to 0.42.1
After upgrading 2 files cause ktlint to fail with an Internal Error (indent)
[SettlementsSpec.kt.zip](https://github.com/pinterest/ktlint/files/6966917/SettlementsSpec.kt.zip)
[generators.kt.zip](https://github.com/pinterest/ktlint/files/6966925/generators.kt.zip)

## Expected Behavior
the file should get formatted

## Observed Behavior
SettlementsSpec.kt:0:0: Internal Error (indent). Please create a ticket at https://github.com/pinterest/ktlint/issues (if possible, provide the source code that triggered an error) (cannot be auto-corrected)

## Steps to Reproduce
Format the attached file 

## Your Environment
* Version of ktlint used: 0.42.1
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task):
Gradle Task:
task ktlintFmt(type: JavaExec) {
    mainClass.set("com.pinterest.ktlint.Main")
    classpath = configurations.ktlint
    args "-F", "src/**/*.kt"
    onlyIf {
        System.env['CI'] == null
    }
}
* Version of Gradle used (if applicable): 7.1.1
* Operating System and version: MacOS Big Sur
* Link to your project (if it's a public repository):

### PR DESCRIPTION
**Pull request by paul-dingemans**
## Description

Forces the BY keyword in a super type call entry to be indented when preceded by a new line

The code sample from issue #1210 is now formatted as:
```
object ApplicationComponentFactory : ApplicationComponent.Factory
    by DaggerApplicationComponent.factory()
```

As a side effect, this also formats
```
class Test2 : Foo
by Bar(
    a = 1,
    b = 2,
    c = 3
)
```
to
```
class Test2 : Foo
    by Bar(
        a = 1,
        b = 2,
        c = 3
    )
```

Closes #1210

## Checklist

- [X] tests are added
- [X] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by romtsn** [comment]
Hm, when I throw this code into IJ, it actually keeps it unchanged:
```
class Test2 : Foo
by Bar(
    a = 1,
    b = 2,
    c = 3
)
```

Should we maybe just make sure that it doesn't fail, but follow IJ's formatting in this case? Note, however, that this case is fine:
```
class Test2 : 
    Foo
    by Bar(
        a = 1,
        b = 2,
        c = 3
    )
```

**Comment by paul-dingemans** [comment]
You're right. We should not conflict with IntelliJ default of formatting case below:
```
class Test2 : Foo
by Bar(
    a = 1,
    b = 2,
    c = 3
)
```

Let me try to fix this one before merging.

**Comment by paul-dingemans** [comment]
> @paul-dingemans let me know if/when this is ready for merging.

@shashachu Merge conflict is resolved. It is ready to be merged.

**Comment by romtsn** [comment]
@paul-dingemans but have you addressed the comment I left? the test is kinda still not looking compatible with IJ
image

**Comment by paul-dingemans** [comment]
@romtsn @shashachu I am sorry. I only focussed at the merge conflict. I did not read the history carefully enough. I will address or submit a PR to revert this tomorrow.

**Comment by romtsn** [comment]
awesome, thanks 👍

**Comment by paul-dingemans** [comment]
> I will address or submit a PR to revert this tomorrow.

@shashachu @romtsn I have it solved on my local machine. Code however is not production ready yet. Will continue tomorrow.

**Comment by paul-dingemans** [comment]
> @romtsn @shashachu I am sorry. I only focussed at the merge conflict. I did not read the history carefully enough. I will address or submit a PR to revert this tomorrow.

@romtsn @shashachu See https://github.com/pinterest/ktlint/pull/1322 for fix.

**Pull request merged**
