### PR TITLE
Print errors, tracing and debugging information to stderr instead of stdout

### LINKED ISSUE #1137: Broken output JSON with warnings
## Expected Behavior

`ktlint --reporter json` should output a valid JSON to STDOUT even if warnings are present.

For example, when running `ktlint Foo.kt --reporter json > ktlint-out.json`, `ktlint-out.json` should be a valid JSON file.

## Observed Behavior

Output JSON includes the following warning messages, so the JSON is invalid.

```
[WARNING] `ascii` is deprecated! Please use `*` instead to ensure that the Kotlin IDE plugin recognizes the value
[WARNING] `kotlin_imports_layout` is deprecated! Please use `ij_kotlin_imports_layout` to ensure that the Kotlin IDE plugin and ktlint use same imports layout
```

## Steps to Reproduce

1. Create `.editorconfig` file:
 
```editorconfig
root = true

[*]
charset = utf-8
end_of_line = lf
trim_trailing_whitespace = true
insert_final_newline = true
indent_style = space
indent_size = 2

[*.{kt,kts}]
kotlin_imports_layout=ascii
```

2. Create a sample Kotlin file, e.g. `Foo.kt`:

```kotlin
class Foo {
}
```

3. Run `ktlint Foo.kt --reporter json > ktlint-out.json`. The content of `ktlint-out.json` will be:

```
[WARNING] `ascii` is deprecated! Please use `*` instead to ensure that the Kotlin IDE plugin recognizes the value
[WARNING] `kotlin_imports_layout` is deprecated! Please use `ij_kotlin_imports_layout` to ensure that the Kotlin IDE plugin and ktlint use same imports layout
[
	{
		"file": "/work/Foo.kt",
		"errors": [
			{
				"line": 1,
				"column": 11,
				"message": "Unnecessary block (\"{}\")",
				"rule": "no-empty-class-body"
			}
		]
	}
]
```

This output JSON file is invalid. We can confirm it via `jq`, for example:

```console
$ jq . < ktlint-out.json
parse error: Invalid numeric literal at line 1, column 9
```

## Your Environment

* Version of ktlint used: 0.41.0
* Name and version (or code for custom task) of integration used (Gradle plugin, Maven plugin, command line, custom Gradle task): command line
* Version of Gradle used (if applicable): N/A
* Operating System and version: Debian GNU/Linux 10 (buster)
* Link to your project (if it's a public repository): N/A

### PR DESCRIPTION
**Pull request by paul-dingemans**
## Description

Ideally only the output of rule violations is printed to stdout so that it can be redirected
to the reporters. Normal log lines most likely break the format of the reporter and therefore
should be printed to stderr.

Closes #1137

## Checklist

- [ ] tests are added
- [X] `CHANGELOG.md` is updated

### CODE REVIEW

**Comment by romtsn** [comment]
I believe @Tapchicoma had a slightly different idea - to use some proper logging solution for that -> https://github.com/pinterest/ktlint/issues/589 

(here comes the joke about log4j indeed)

**Comment by paul-dingemans** [comment]
> I believe @Tapchicoma had a slightly different idea - to use some proper logging solution for that -> #589
> 
> (here comes the joke about log4j indeed)

In the end that will be a better solution. Meanwhile, this PR still adds value as it once more has been checked that no output is written to stdout that interferes with the reporters.

**Comment by paul-dingemans** [comment]
> > I believe @Tapchicoma had a slightly different idea - to use some proper logging solution for that -> #589
> > (here comes the joke about log4j indeed)
> 
> In the end that will be a better solution. Meanwhile, this PR still adds value as it once more has been checked that no output is written to stdout that interferes with the reporters.

@romtsn See https://github.com/pinterest/ktlint/pull/1327 for implementation of logging framework. This PR can be closed once that PR has been approved and merged.

**Comment by romtsn** [comment]
yeah let's try to push #1327 through, closing this

**Pull request closed without merging**
