### PR TITLE
Add M1 Finance to list of adopters

### PR DESCRIPTION
**Pull request by EricKuck**

### CODE REVIEW

**Comment by Tapchicoma** [comment]
Are you a developer at "M1 Finance"? It is not visible from your Github profile :disappointed_relieved: 

For context, see https://github.com/pinterest/ktlint/pull/571#issuecomment-531903086

**Comment by EricKuck** [comment]
Yes, I am a developer for M1. The PR was made from the M1 organization, not my personal account, which I’m assuming should be evidence that M1 is a user?

**Comment by Tapchicoma** [comment]
Yes, just commenting in this PR from your work account should be enough.

**Comment by EricKuck** [comment]
Sorry, I'm confused. I don't have a work GitHub account. Are you saying that the PR coming from the m1finance organization's account isn't enough?

**Comment by Tapchicoma** [comment]
Sorry, missed that part. Should be fine :+1:

**Comment by EricKuck** [comment]
Cool, thanks!

**Pull request merged**
