### PR TITLE
Process of migrating to gradle - organize gradle dependencies

### PR DESCRIPTION
**Pull request by jaredsburrows**
#445

@shashachu

Clean up and organize Gradle dependencies across the project. This is similar to other open source Gradle projects such as https://github.com/JakeWharton/SdkSearch/blob/master/build.gradle#L18.

### CODE REVIEW

**Comment by shashachu** [comment]
Interesting! I've never seen this particular format. Very nice.

**Comment by shashachu** [comment]
BTW, probably outside the scope of this migration, but I'd love to eventually port the build scripts to kotlin as well.

**Comment by jaredsburrows** [comment]
@shashachu I can make a PR for that as well.

**Comment by rom4ek** [comment]
@jaredsburrows Btw, it's already too late to ask, but is there a specific reason of not using the `implementation`/`api` instead of `compile`? Just noticed that.

**Comment by jaredsburrows** [comment]
@rom4ek This CL was to organize the dependencies.

**Pull request merged**
